name: "Godot Cloud Build"

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Godot Export
        uses: firebelley/godot-export@v6.0.0
        with:
          # Usamos los mirrors de GitHub Releases en lugar de TuxFamily
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.7.1-stable/Godot_v4.7.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.7.1-stable/Godot_v4.7.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Juego-Compilado
          path: /github/workspace/build/**
